version: "3.8"
services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    ports:
      - "4444:4444"
    shm_size: 2g

  html-server:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./healthtrack/web:/usr/share/nginx/html:ro

  maven:
    image: maven:3.9-eclipse-temurin-17
    depends_on:
      - selenium
      - html-server
    volumes:
      - ./healthtrack:/usr/src/app
    working_dir: /usr/src/app
    environment:
      SELENIUM_REMOTE_URL: http://selenium:4444/wd/hub
    command: >
      sh -c "
        apt-get update && apt-get install -y curl &&
        echo '⏳ Esperando a que Selenium esté listo...' &&
        until curl -s http://selenium:4444/wd/hub/status | grep -q '\"ready\": true'; do
          sleep 1;
        done &&
        echo '✅ Selenium está listo. Ejecutando pruebas...' &&
        mvn test
      "
