version: "3.8"
services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    ports:
      - "4444:4444"
    shm_size: 2g

  html-server:
    image: python:3
    container_name: html-server
    working_dir: /usr/src/app
    volumes:
      - ./healthtrack/web:/usr/src/app
    command: python3 -m http.server 8000
    ports:
      - "8000:8000"
