name: Java + Selenium CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    
      - name: Clona el repo
        uses: actions/checkout@v3

      - name: Instala Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose


      - name: Levanta servicios con docker-compose
        run: docker compose up -d selenium html-server


      - name: Espera a que Selenium esté listo (respuesta HTTP 200 en /status)
        run: |
          for i in {1..30}; do
            echo "Esperando Selenium... intento $i"
            if curl -s http://localhost:4444/status | grep -q '"ready":true'; then
              echo "Selenium está listo ✅"
              break
            fi
            sleep 2
          done

      - name: Ejecuta los tests con Maven en el contenedor
        run: docker compose run --rm maven mvn test

      - name: Ejecutar pruebas JMeter con Docker Compose
        run: docker compose up --abort-on-container-exit jmeter

      - name: Guardar resultados de JMeter como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-resultados
          path: jmeter/resultados/resultados.jtl

      - name: Apaga los contenedores
        run: docker compose down