name: Java CI con Selenium

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g
        
        html-server:
        image: python:3
        ports:
          - 8000:8000
        volumes:
          - ./web:/usr/src/app
        working-directory: /usr/src/app
        command: python3 -m http.server 8000

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compilar y ejecutar pruebas
        run: |
          cd tests
          SELENIUM_REMOTE_URL=http://localhost:4444/wd/hub mvn test